# Generated by Django 2.2.10 on 2020-03-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200312_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.FileField(upload_to='team_imgs'),
        ),
    ]
