# Generated by Django 2.2.10 on 2020-03-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_team_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerseason',
            name='total',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
